# Generated by Django 4.1.6 on 2023-02-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_table',
            name='Img_items',
            field=models.CharField(default='https://images.unsplash.com/photo-1671221464173-823f79579e31?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80', max_length=500),
        ),
    ]
