# Generated by Django 4.1.6 on 2023-02-09 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_table_img_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_table',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
